<?php

function kolding_modules_menu() {
 	$items['admin/settings/kolding'] = array(
    'title' => 'Kolding Library settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kolding_modules_settings_form'),
    'access arguments' => array('configure libraries'),
  );

  return $items;
}

function kolding_modules_settings_form($form_state){
	
	$form['kolding_modules'] = array(
    '#type'          => 'textarea',
    '#title'         => t('Materiale valg'),
    '#description'   => t(''),
    '#required'      => FALSE,
    '#default_value' => variable_get('kolding_modules', ''),
  );
 
  return system_settings_form($form);
	
}


// Drupal needs this blank file.

function kolding_modules_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'user_login_block'){
    
    #var_dump($form);
    
    $form['name']['#prefix'] = '<p>log ind &gt;</p>';
    $form['name']['#title'] = t('CPR Lånernr.');
    $form['pass']['#title'] = t('Pinkode');
    $form['submit']['#type'] = 'image_button';
    $form['submit']['#src'] = drupal_get_path('theme','kolding').'/images/logindknap.png';
  }
}


function kolding_modules_form_ting_search_form_alter(&$form,&$form_state){
  //dsm($form);
  
  $form['keys']['#weight'] = 1;
  $form['example_text']['#weight'] = 4;
  $form['example_text']['#value'] = '<div class="example"><p>'.t('eksempel menu').'</p></div>';
  
  $options = array();
  if(variable_get('kolding_modules', '') != ''){
  	$rows = explode("\n",variable_get('kolding_modules', ''));
  }
  
  foreach ($rows as $value){
  	$value = explode('|',$value);
  	$options[$value[0]] = $value[1];
  }
  
  $form['submit']['#weight'] = 3;
  $form['type'] = array(
    '#weight' => 2,
    '#type' => 'select',
    '#options' => $options,
    '#attributes' => array('class' => 'select-type-field'),
  ); 
}

function kolding_modules_menu_alter(&$items) {
 
  $items['ting/search']['page callback'] = 'kolding_modules_ting_search_pages_redirect';
   
  return $items;
}
  
/**
 * Search result page.
 */
function kolding_modules_ting_search_pages_redirect() {

  if (isset($_POST['keys'])) {
    if($_POST['type']){
      $extend = 'facets=facet.type:'.$_POST['type'].';';
    }
    return drupal_goto('ting/search/' . $_POST['keys'],'',$extend);
  }

  $keys = search_get_keys();
  if (strlen($keys) > 0) {
    // Redirect to the new Panels based search.
    return drupal_goto('ting/search/' . $keys, NULL, NULL, 301);
  }
  return drupal_not_found();
}
include_once('kolding_modules.features.inc');