<?php

/**
 * Implementation of hook_init().
 */
function kolding_modules_init() {
  // AddThis is integrated into the page template so addthis_add_default_js gets called too
  // late in the process. We add it here instead.
  if(module_exists('addthis')) {
    addthis_add_default_js();
  }
}

/**
 * Implementation of hook_addthis_toolbox_services_alter().
 */
function kolding_modules_addthis_toolbox_services_alter(&$services) {
  $services['more']['title'] = t('More');
  $services['facebook'] = array('class' => 'addthis_button_facebook',
  															'title' => t('Share on Facebook'));
}

function kolding_modules_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'user_login_block'){
    $form['name']['#prefix'] = '<p>' . t('Log ind &gt;') . '</p>';
    $form['name']['#title'] = t('CPR Lånernr.');
    $form['pass']['#title'] = t('Pinkode');
    $form['submit']['#type'] = 'image_button';
    $form['submit']['#src'] = drupal_get_path('theme','kolding').'/images/logindknap.png';
  }
}

function kolding_modules_form_ting_search_form_alter(&$form,&$form_state){
  $form['keys']['#weight'] = 1;
  $form['example_text']['#weight'] = 4;
  $form['example_text']['#value'] = '<div class="example"><p>'.t('eksempel menu').'</p></div>';
}


include_once('kolding_modules.features.inc');